[package]
name = "test-go-mcp-pattern"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde_json = "1.0"
anyhow = "1.0"

[[bin]]
name = "test_go_mcp"
path = "test_go_mcp_pattern.rs" 